/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FabricDeploy;

import org.yaml.snakeyaml.Yaml;

public class Library {
    public boolean someLibraryMethod() {
    	Yaml yaml = new Yaml();
        return true;
    }
}
